### ISSUE TITLE
Phonopy example in website uses deprecated syntax

### ISSUE THREAD

**Issue by cw-tan** [profess-dev/profess#16]
Using `Phonopy 2.17.1`, the syntax used in the Gibbs free energy example in the website is considered deprecated. For example:
`DeprecationWarning: PhonopyQHA.get_gibbs_temperature() is deprecated.Use gibbs_temperature attribute.`
`DeprecationWarning: Phonopy.get_displacements() is deprecated.Use Phonopy.displacements attribute.`

I can do a pull request to fix this - do I just need to edit the code in `profess/website/source/examples/gibbs.md` and the website will be updated automatically after the acceptance of the pull request? Maybe it's useful if I also add in the text that the example uses `Phonopy 2.17.1`.

**Comment by wcwitt** [comment]
Thanks, I’ll fix this

**Comment by wcwitt** [comment]
I believe this is fixed by 5dcef9b229bba66d47bf3980175935606ec91715. Do you agree?

**Comment by cw-tan** [comment]
Yup, agreed. Copy-pasting the code and running it worked without any errors. Thanks!
